# Generated by Django 5.1.4 on 2025-08-28 14:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devotee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter 10 digit mobile number')])),
                ('aadhaar_last4', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$')])),
                ('aadhaar_hash', models.CharField(help_text='SHA256 of full Aadhaar for de-duplication', max_length=64)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('token', models.CharField(db_index=True, max_length=20, unique=True)),
                ('diwali_year', models.IntegerField(help_text='Diwali cycle year (e.g., 2025)')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('HELD', 'Held in Temple'), ('RETURNED', 'Returned to Devotee'), ('CANCELLED', 'Cancelled')], default='HELD', max_length=10)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='vault.devotee')),
            ],
        ),
    ]
