# Generated by Django 5.1.4 on 2025-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='aadhaar_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='aadhaar_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
