# Generated by Django 5.0.6 on 2025-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_devotee_email_alter_devotee_aadhaar_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='form_filler_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
