# Generated by Django 5.0.6 on 2025-09-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_deposit_comment_deposit_form_filler_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='comment',
        ),
        migrations.AddField(
            model_name='deposit',
            name='comment_choice',
            field=models.CharField(blank=True, choices=[('First Time', 'First Time'), ('Regular Devotee', 'Regular Devotee'), ('VIP', 'VIP'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
