# Generated by Django 5.0.6 on 2025-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_remove_deposit_comment_deposit_comment_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='comment_choice',
            field=models.CharField(blank=True, choices=[('₹1 (New)', '₹1 (New)'), ('₹1 (Old)', '₹1 (Old)'), ('₹2 (New)', '₹2 (New)'), ('₹2 (Old)', '₹2 (Old)'), ('₹5 (New)', '₹5 (New)'), ('₹5 (Old)', '₹5 (Old)'), ('₹10 (New)', '₹10 (New)'), ('₹10 (Old)', '₹10 (Old)'), ('₹20 (New)', '₹20 (New)'), ('₹20 (Old)', '₹20 (Old)'), ('₹50 (New)', '₹50 (New)'), ('₹50 (Old)', '₹50 (Old)'), ('₹100 (New)', '₹100 (New)'), ('₹100 (Old)', '₹100 (Old)'), ('₹200 (New)', '₹200 (New)'), ('₹200 (Old)', '₹200 (Old)'), ('₹500 (New)', '₹500 (New)'), ('₹500 (Old)', '₹500 (Old)')], max_length=50, null=True),
        ),
    ]
