# Generated by Django 5.0.6 on 2025-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_alter_deposit_comment_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='comment_choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
