# Generated by Django 5.0.6 on 2025-09-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_deposit_comment_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
