# Generated by Django 5.0.6 on 2025-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_deposit_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotee',
            name='aadhaar_hash',
            field=models.CharField(max_length=64),
        ),
    ]
